--a)

--DISTINCT
SELECT DISTINCT C.NMPRODUCT
FROM PRODUCTREQUEST PR

INNER JOIN PRODUCT C ON PR.CDPRODUCT = C.CDPRODUCT 

--GROUP BY
SELECT C.NMPRODUCT
FROM PRODUCTREQUEST PR
INNER JOIN PRODUCT C ON PR.CDPRODUCT = C.CDPRODUCT 
GROUP BY C.NMPRODUCT;

--b)

SELECT
    P.NMPRODUCT,
    COUNT(PR.CDREQUEST) AS VEZESPEDIDO,
    SUM(PR.QTAMOUNT) AS QTPEDIDA

FROM PRODUCTREQUEST PR INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

GROUP BY P.NMPRODUCT;

--c)

SELECT
    S.NMSUPPLIER,
    SUM(P.QTSTOCK) AS TOTALSTOK,
    AVG(P.VLPRICE) AS MÉDIAPREÇO,
    COUNT(P.CDPRODUCT) AS QTPRODUCTFORNCEIDOS

FROM SUPPLIER S INNER JOIN PRODUCT P ON S.CDSUPPLIER = P.CDSUPPLIER

GROUP BY S.NMSUPPLIER;

--d)

SELECT C.NMCUSTOMER, 
C.IDFONE, 
MAX(R.VLTOTAL) AS VLMAIORCOMPRA, 
MIN(R.VLTOTAL) AS VLMENORCOMPRA, 
SUM(R.VLTOTAL) AS TOTALCOMPRADO,
AVG((R.VLTOTAL)) AS MEDIAVLCOMPRADO

FROM CUSTOMER C INNER JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER

GROUP BY C.NMCUSTOMER, C.IDFONE

ORDER BY MAX(R.VLTOTAL) DESC;

--e)

SELECT R.DTREQUEST,
C.NMCUSTOMER, 
COUNT(DISTINCT(PR.CDPRODUCT))AS QTPRODUCTDISTINTOS, 
SUM(PR.QTAMOUNT * PR.VLUNITARY) AS VLTOTALPED,
AVG(PR.QTAMOUNT * PR.VLUNITARY) AS MEDIAVLPEDIDO

FROM REQUEST R

INNER JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST

GROUP BY C.NMCUSTOMER, R.DTREQUEST 


--f)

SELECT S.NMSUPPLIER, COUNT(P.CDPRODUCT) AS QTPRODUCTFORNECIDOS

FROM SUPPLIER S INNER JOIN PRODUCT P ON S.CDSUPPLIER = P.CDSUPPLIER

GROUP BY S.NMSUPPLIER

HAVING COUNT(P.CDPRODUCT) > 1

--g)

SELECT
    P.NMPRODUCT,
    COUNT(PR.CDREQUEST) AS VEZESPEDIDO,
    SUM(PR.QTAMOUNT) AS QTPEDIDA

FROM PRODUCTREQUEST PR INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

GROUP BY P.NMPRODUCT

HAVING COUNT(PR.CDREQUEST) < 2;

--h)

SELECT C.NMCUSTOMER,
P.NMPRODUCT, 
(PR.QTAMOUNT * PR.VLUNITARY) AS VLGASTO,
COUNT(DISTINCT(PR.CDPRODUCT)) AS VEZESPEDIDO,
S.NMSUPPLIER

FROM CUSTOMER C

INNER JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
INNER JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER

WHERE (PR.QTAMOUNT * PR.VLUNITARY) > 1000

GROUP BY C.NMCUSTOMER, P.NMPRODUCT, S.NMSUPPLIER, PR.QTAMOUNT, PR.VLUNITARY


ORDER BY C.NMCUSTOMER, P.NMPRODUCT