--a)

USE L2

SELECT
NMCUSTOMER,
IDFONE FROM CUSTOMER WHERE IDFONE LIKE '4%'


--b)

SELECT * FROM CUSTOMER WHERE IDFONE = ''

--c)

SELECT NMSUPPLIER, IDFONE FROM SUPPLIER WHERE LEN(IDFONE) < 8

--d)

SELECT NMPRODUCT,
QTSTOCK,
VLPRICE - (VLPRICE * 0.1) AS VLPRICE FROM PRODUCT P WHERE P.QTSTOCK > 2000; 

--e)

SELECT NMPRODUCT,
VLPRICE FROM PRODUCT P WHERE P.VLPRICE BETWEEN 10 AND 20

--f)

SELECT NMPRODUCT,
VLPRICE, (VLPRICE * QTSTOCK) AS VLTOTAL FROM PRODUCT P WHERE P.VLPRICE >50

--g)

SELECT P.NMPRODUCT,
S.NMSUPPLIER,
S.IDFONE FROM PRODUCT P INNER JOIN SUPPLIER S ON S.CDSUPPLIER = P.CDSUPPLIER

WHERE p.VLPRICE > 20 AND P.QTSTOCK > 1500 

--h)

SELECT C.NMCUSTOMER,
R.DTREQUEST,
R.VLTOTAL

FROM REQUEST R INNER JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER

WHERE R.DTREQUEST BETWEEN '2003-06-01' AND '2003-07-31'

--i)

SELECT C.NMCUSTOMER,
       P.NMPRODUCT,
       R.DTREQUEST,
       PR.QTAMOUNT,
       PR.VLUNITARY,
       (PR.QTAMOUNT * PR.VLUNITARY) AS VLTOTALPEDIDO
FROM REQUEST R

INNER JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

WHERE PR.QTAMOUNT > 500