USE L1
 
CREATE TABLE SUPPLIER(
CDSUPPLIER INT,
NMSUPPLIER VARCHAR(50),
NRFONE NUMERIC(12),
)
 
CREATE TABLE PRODUCT(
CDPRODUCT INT,
NMPRODUCT VARCHAR(50),
CDSUPPLIER INT,
VLPRICE MONEY,
QTSTOCK INT,
)
 
CREATE TABLE PRODUCTREQUEST(
CDREQUEST INT,
CDPRODUCT INT,
QTAMOUNT INT,
VLUNITARY MONEY,
)
 
CREATE TABLE REQUEST(
CDREQUEST INT,
DTREQUEST DATE,
CDCOSTUMER INT,
DTDELIVER DATE,
VLTOTAL MONEY,
)
 
CREATE TABLE COSTUMER(
CDCOSTUMER INT,
NMCOSTUMER VARCHAR(50),
NRFONE NUMERIC(12),
DSADRESS VARCHAR(255)
)

-------

USE L1

ALTER TABLE SUPPLIER alter column CDSUPPLIER int NOT NULL;
ALTER TABLE SUPPLIER alter column NMSUPPLIER VARCHAR(50) NOT NULL;
ALTER TABLE SUPPLIER alter column NRFONE NUMERIC(12) NOT NULL;

ALTER TABLE PRODUCT alter column CDPRODUCT int NOT NULL;
ALTER TABLE PRODUCT alter column NMPRODUCT VARCHAR(50) NOT NULL;
ALTER TABLE PRODUCT alter column CDSUPPLIER int NOT NULL;
ALTER TABLE PRODUCT alter column VLPRICE MONEY NOT NULL;
ALTER TABLE PRODUCT alter column QTSTOCK int NOT NULL;

ALTER TABLE PRODUCTREQUEST alter column CDREQUEST int NOT NULL;
ALTER TABLE PRODUCTREQUEST alter column CDPRODUCT int NOT NULL;
ALTER TABLE PRODUCTREQUEST alter column QTAMOUNT int NOT NULL;
ALTER TABLE PRODUCTREQUEST alter column VLUNITARY MONEY NOT NULL;

ALTER TABLE REQUEST alter column CDREQUEST int NOT NULL;
ALTER TABLE REQUEST alter column DTREQUEST DATE NOT NULL;
ALTER TABLE REQUEST alter column CDCOSTUMER int NOT NULL;
ALTER TABLE REQUEST alter column DTDELIVER DATE NOT NULL;
ALTER TABLE REQUEST alter column VLTOTAL MONEY NOT NULL;

ALTER TABLE COSTUMER alter column CDCOSTUMER int NOT NULL;
ALTER TABLE COSTUMER alter column NMCOSTUMER VARCHAR(50) NOT NULL;
ALTER TABLE COSTUMER alter column NRFONE NUMERIC(12) NOT NULL;
ALTER TABLE COSTUMER alter column DSADRESS VARCHAR(255) NOT NULL;

-------

USE L1
 
ALTER TABLE SUPPLIER
ADD PRIMARY KEY (CDSUPPLIER);
 
ALTER TABLE PRODUCT
ADD PRIMARY KEY (CDPRODUCT);

ALTER TABLE REQUEST
ADD PRIMARY KEY (CDREQUEST);

ALTER TABLE COSTUMER
ADD PRIMARY KEY (CDCOSTUMER);

ALTER TABLE PRODUCTREQUEST
ADD PRIMARY KEY (CDREQUEST, CDPRODUCT);

-------

USE L1

ALTER TABLE PRODUCT 
ADD CONSTRAINT FK_SUPPLIER FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER(CDSUPPLIER)

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_REQUEST FOREIGN KEY (CDREQUEST) REFERENCES REQUEST(CDREQUEST)

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT(CDPRODUCT)

ALTER TABLE REQUEST 
ADD CONSTRAINT FK_COSTUMER FOREIGN KEY (CDCOSTUMER) REFERENCES COSTUMER(CDCOSTUMER) 
