-- a)

USE lista1
 
CREATE TABLE SUPPLIER(
CDSUPPLIER INT IDENTITY(1,1),
NMSUPPLIER VARCHAR(50),
NRFONE NUMERIC(12),
)
 
CREATE TABLE PRODUCT(
CDPRODUCT INT IDENTITY(1,1),
NMPRODUCT VARCHAR(50),
CDSUPPLIER INT,
VLPRICE MONEY,
QTSTOCK INT,
)
 
CREATE TABLE PRODUCTREQUEST(
CDREQUEST INT,
CDPRODUCT INT,
QTAMOUNT INT,
VLUNITARY MONEY,
)
 
CREATE TABLE REQUEST(
CDREQUEST INT IDENTITY(1,1),
DTREQUEST DATE,
CDCOSTUMER INT,
DTDELIVER DATE,
VLTOTAL MONEY,
)
 
CREATE TABLE COSTUMER(
CDCOSTUMER INT IDENTITY(1,1),
NMCOSTUMER VARCHAR(50),
NRFONE NUMERIC(12),
DSADRESS VARCHAR(255)
)

-------

USE lista1

ALTER TABLE SUPPLIER alter column CDSUPPLIER int NOT NULL;
ALTER TABLE SUPPLIER alter column NMSUPPLIER VARCHAR(50) NOT NULL;
ALTER TABLE SUPPLIER alter column NRFONE NUMERIC(12) NOT NULL;

ALTER TABLE PRODUCT alter column CDPRODUCT int NOT NULL;
ALTER TABLE PRODUCT alter column NMPRODUCT VARCHAR(50) NOT NULL;
ALTER TABLE PRODUCT alter column CDSUPPLIER int NOT NULL;
ALTER TABLE PRODUCT alter column VLPRICE MONEY NOT NULL;
ALTER TABLE PRODUCT alter column QTSTOCK int NOT NULL;

ALTER TABLE PRODUCTREQUEST alter column CDREQUEST int NOT NULL;
ALTER TABLE PRODUCTREQUEST alter column CDPRODUCT int NOT NULL;
ALTER TABLE PRODUCTREQUEST alter column QTAMOUNT int NOT NULL;
ALTER TABLE PRODUCTREQUEST alter column VLUNITARY MONEY NOT NULL;

ALTER TABLE REQUEST alter column CDREQUEST int NOT NULL;
ALTER TABLE REQUEST alter column DTREQUEST DATE NOT NULL;
ALTER TABLE REQUEST alter column CDCOSTUMER int NOT NULL;
ALTER TABLE REQUEST alter column DTDELIVER DATE NOT NULL;
ALTER TABLE REQUEST alter column VLTOTAL MONEY NOT NULL;

ALTER TABLE COSTUMER alter column CDCOSTUMER int NOT NULL;
ALTER TABLE COSTUMER alter column NMCOSTUMER VARCHAR(50) NOT NULL;
ALTER TABLE COSTUMER alter column NRFONE NUMERIC(12) NOT NULL;
ALTER TABLE COSTUMER alter column DSADRESS VARCHAR(255) NOT NULL;

-- b)

USE lista1
 
ALTER TABLE SUPPLIER
ADD PRIMARY KEY (CDSUPPLIER);
 
ALTER TABLE PRODUCT
ADD PRIMARY KEY (CDPRODUCT);

ALTER TABLE REQUEST
ADD PRIMARY KEY (CDREQUEST);

ALTER TABLE COSTUMER
ADD PRIMARY KEY (CDCOSTUMER);

ALTER TABLE PRODUCTREQUEST
ADD PRIMARY KEY (CDREQUEST, CDPRODUCT);

-- c)

USE lista1

ALTER TABLE PRODUCT 
ADD CONSTRAINT FK_SUPPLIER FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER(CDSUPPLIER)

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_REQUEST FOREIGN KEY (CDREQUEST) REFERENCES REQUEST(CDREQUEST)

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT(CDPRODUCT)

ALTER TABLE REQUEST 
ADD CONSTRAINT FK_COSTUMER FOREIGN KEY (CDCOSTUMER) REFERENCES COSTUMER(CDCOSTUMER) 

-- d)

USE lista1

CREATE INDEX IDXSUPPLIER ON PRODUCT(CDSUPPLIER);


-- e)

USE lista1

CREATE INDEX IDXCOSTUMER ON REQUEST(CDCOSTUMER);

-- f)

USE lista1

ALTER TABLE SUPPLIER 
ADD ADRESS VARCHAR(255);

-- g)

USE lista1

INSERT INTO COSTUMER (NMCOSTUMER, NRFONE, DSADRESS) 
VALUES ('Fabiano', 99879375, 'Rua Tijucas, 110, Centro, Joinville - S.C'); 

-- h)

USE lista1;

INSERT INTO REQUEST(DTREQUEST, CDCOSTUMER, DTDELIVER, VLTOTAL)
VALUES ('2008/01/31', 1, '2008/02/05', 54.00)

SELECT

R.CDREQUEST,
R.DTREQUEST,
R.CDCOSTUMER,
R.DTDELIVER,
R.VLTOTAL,
C.NMCOSTUMER

FROM REQUEST R
	INNER JOIN COSTUMER C ON R.CDCOSTUMER = C.CDCOSTUMER
;

-- i)

USE lista1;

 UPDATE COSTUMER
 SET NRFONE = 99012567
 WHERE CDCOSTUMER = 1;  
 

-- j)

USE lista1;


DELETE FROM REQUEST
WHERE CDREQUEST = 1

DELETE FROM COSTUMER
WHERE CDCOSTUMER = 1

-- k)

 USE lista1

DROP TABLE dbo.PRODUCTREQUEST;  
DROP TABLE dbo.PRODUCT;  
DROP TABLE dbo.REQUEST;  
DROP TABLE dbo.COSTUMER;  
DROP TABLE dbo.SUPPLIER;  