--a)

SELECT
    P.NMPRODUCT,
    COUNT(PR.CDREQUEST) AS VEZESPEDIDO

FROM PRODUCTREQUEST PR INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

GROUP BY P.NMPRODUCT;

--b)

SELECT
    S.NMSUPPLIER,
    COUNT(P.CDPRODUCT) AS NMRPRODUCTSFORNECIDOS

FROM PRODUCT P INNER JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER

GROUP BY S.NMSUPPLIER 

--c)

SELECT
    S.NMSUPPLIER,
    P.NMPRODUCT,
    COUNT(PR.QTAMOUNT) AS QTPRODUTOSVENDIDOS

FROM SUPPLIER S

INNER JOIN PRODUCT P ON S.CDSUPPLIER = P.CDSUPPLIER
INNER JOIN PRODUCTREQUEST AS PR ON P.CDPRODUCT = PR.CDPRODUCT
GROUP BY S.NMSUPPLIER, P.NMPRODUCT WITH ROLLUP;

--d)

SELECT
    C.NMCUSTOMER,
    P.NMPRODUCT,
    COUNT(PR.VLUNITARY) AS VGASTOCPRODUTO

FROM CUSTOMER C

INNER JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

GROUP BY C.NMCUSTOMER, P.NMPRODUCT WITH ROLLUP;


--e)

SELECT C.NMCUSTOMER, C.IDFONE

FROM CUSTOMER C 

LEFT JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER

WHERE R.CDCUSTOMER IS NULL


--f)

SELECT S.NMSUPPLIER, S.IDFONE 

FROM SUPPLIER S

INNER JOIN PRODUCT P ON S.CDSUPPLIER = P.CDSUPPLIER

WHERE P.NMPRODUCT LIKE '%leite em po%' OR P.NMPRODUCT LIKE '%agua mineral%'

--g)

SELECT S.NMSUPPLIER, P.NMPRODUCT

FROM PRODUCT P

INNER JOIN SUPPLIER S ON P.CDSUPPLIER = S.CDSUPPLIER
INNER JOIN PRODUCTREQUEST PR ON P.CDPRODUCT = PR.CDPRODUCT

GROUP BY S.NMSUPPLIER, P.NMPRODUCT

HAVING COUNT(PR.CDREQUEST) > 3