--a)

DELETE FROM REQUEST
WHERE VLTOTAL < 1000.00
AND CDREQUEST NOT IN (SELECT CDREQUEST FROM PRODUCTREQUEST)
AND MONTH(DTREQUEST) = 6
AND YEAR(DTREQUEST) = 2003

--b)

UPDATE PRODUCT
SET VLPRICE = (SELECT AVG(PR.VLUNITARY) FROM PRODUCTREQUEST PR)
WHERE CDPRODUCT IN ( SELECT CDPRODUCT FROM PRODUCTREQUEST GROUP BY CDPRODUCT HAVING SUM(QTAMOUNT) < 800 )

--c)

INSERT INTO CUSTOMER (CDCUSTOMER, NMCUSTOMER, IDFONE, NMADRESS)

SELECT (SELECT (MAX(CDCUSTOMER)) FROM CUSTOMER) + S.CDSUPPLIER 
	AS CDCUSTOMER,
       S.NMSUPPLIER,
       S.IDFONE,
 '' AS NMADRESS
FROM SUPPLIER S;

--d)

UPDATE REQUEST
SET DTDELIVER = DATEADD(day, 30, DTDELIVER) 
WHERE DATEDIFF(day, DTREQUEST, DTDELIVER) < 10 AND VLTOTAL < 10000.00
