--1

--a)

DELETE FROM CUSTOMER
WHERE CDCUSTOMER NOT IN (SELECT DISTINCT CDCUSTOMER FROM REQUEST)

--b)

DELETE FROM SUPPLIER
WHERE CDSUPPLIER NOT IN (SELECT DISTINCT CDSUPPLIER FROM PRODUCT);
 
--c) 

UPDATE PRODUCTREQUEST

SET PRODUCTREQUEST.VLUNITARY = PRODUCT.VLPRICE 

FROM PRODUCTREQUEST 
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT 

--d)

ALTER TABLE SUPPLIER 
ADD DSSTATUS VARCHAR(10);

--e)

UPDATE SUPPLIER

SET DSSTATUS = 'INATIVO'

FROM SUPPLIER

WHERE CDSUPPLIER NOT IN (SELECT DISTINCT CDSUPPLIER FROM PRODUCT);

--f)

UPDATE CUSTOMER

SET NMADRESS = 'DESCONHECIDO'

FROM CUSTOMER

WHERE NMADRESS IS NULL

--g)

 INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)

 SELECT R.CDREQUEST, P.CDPRODUCT, 10, P.VLPRICE

 FROM PRODUCTREQUEST PR

 INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
 INNER JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST


--2)

--a)

SELECT P.NMPRODUCT,
C.NMCUSTOMER,
COUNT(PR.CDPRODUCT)AS VEZESCOMPRADO,
SUM(PR.QTAMOUNT) AS TOTALCOMPRADO,
SUM(PR.VLUNITARY * PR.QTAMOUNT) AS VALORPAGOTOTAL

FROM CUSTOMER C

INNER JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

GROUP BY P.NMPRODUCT, C.NMCUSTOMER

--b)

SELECT 
C.NMCUSTOMER,
COUNT(R.CDREQUEST)AS NMRPEDIDOS,
SUM(PR.QTAMOUNT) AS TOTALCOMPRADO

FROM CUSTOMER C

INNER JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT

WHERE R.DTREQUEST LIKE '%2003%'

GROUP BY C.NMCUSTOMER

--c)

SELECT S.NMSUPPLIER, S.IDFONE, P.NMPRODUCT, P.VLPRICE, P.QTSTOCK

FROM SUPPLIER S

LEFT JOIN PRODUCT P ON S.CDSUPPLIER = P.CDSUPPLIER


--d)

SELECT C.NMCUSTOMER, R.DTREQUEST, R.VLTOTAL

FROM CUSTOMER C

LEFT JOIN REQUEST R ON C.CDCUSTOMER = R.CDCUSTOMER

























 
 
 
-- INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
-- SELECT CDREQUEST, CDPRODUCT, 10, VLPRICE
-- FROM REQUEST CROSS JOIN PRODUCT;